server:
  port: 8080

# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sf
    username: root
    password: abcd4567.
  session:
    timeout: 86400
  rabbitmq:
    host: localhost
    port: 5672

like:
  exchange: likeExchange
  queue: likeQueue
  routingKey: likeRoutingKey

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

wx:
  appid: wx317f974906d46cc9
  appsecret: 59e91abc334dfc64b8a6536db57df38b
  signUpTemplateId: 0y74iVIHCLCJJeS-zFL1Q90cFJNjNqQv8TzjMw-cuIQ
  startReminderTemplateId: LVVo1OQ_oe6-hFSJ1yZtsB8odWdA4B8Qg5OdwBVVYWc
  salt: asdcaefevlnshgvihwoieunoviwVEDFXBNDHSDFdfsfsegsefasgaefaf

qiniu:
  access-key: 75CwUTmoxCX0uuB7Wk7TllwblGynoSVTV6fcthdO
  secret-key: TxhCul2aGZ78soJ6BzbfccE4qdLYwHiJZ4zSlv6N
  bucket: ballplus

gd:
  key: 6509cb9d83b3c18f50d9d6a55a205997

